version: "3"
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  tempo:
    image: grafana/tempo
    ports:
      - "4317:4317"
      - "3200:3200"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml"
